export { config }

const config = {
    version: 24,
    accountName: null,

    coins: 0,
    sleds: [],
    trails: [],
    
    coinsCollected: 0,
    totalCoins: 0,
    livesLost: 0,
    livesLostToRocks: 0,
    livesLostToWindCones: 0,
    livesLostToSleds: 0,
    questsComplete: 0,
    questsSkipped: 0,
    totalSession: 0,
    roundsPlayed: 0,
    joinDate: null,
    timesUPressed: 0,
    totalAngleRotated: 0,
    totalHorizontalMovement: 0,
    totalVerticalMovement: 0,
    bestDistance: 0,
    totalDistance: 0,
    bestTime: 0,
    totalTime: 0,
    bestSpeed: 0,
    totalSpeed: 0,


    gameState: null,
    distance: null,
    designWidth: 1918,
    designHeight: 993,

    showHitboxes: false,

    usedSled: null,
    usedTrail: "none",

    playerX: null,
    playerY: null,
    playerRotate: null,
    playerWidth: 80,
    playerHeight: 80,
    lives: null,
    iFrames: null,
    startTime: null,
    endTime: null,

    trailWidth: 30,
    trailHeight: 30,

    baseSpeed: null,
    speed: null,

    obstacleMinSpawn: 600,
    obstacleMaxSpawn: 900,
    rockWidth: 80,
    rockHeight: 80,
    coinWidth: 40,
    coinHeight: 50,
    coneStickWidth: 12,
    coneStickHeight: 19,
    coneWidth: 123,
    coneHeight: 51,

    greenArrowCost: 5,
    blueArrowCost: 5,
    orangeArrowCost: 5,
    purpleArrowCost: 5,
    redSledCost: 10,
    greenSledCost: 10,
    blueSledCost: 10,
    orangeSledCost: 10,
    purpleSledCost: 10,
    duckSledCost: 18,

    redCircleTrailCost: 5,
    greenCircleTrailCost: 5,
    blueCircleTrailCost: 5,
    orangeCircleTrailCost: 5,
    purpleCircleTrailCost: 5,
    starTrailCost: 10,
    heartTrailCost: 10,
    duckSledTrailCost: 18,
    
}