export { config }

const config = {
    version: 25,
    accountName: null,

    coins: 0,
    sleds: [],
    trails: [],
    
    coinsCollected: 0,
    totalCoins: 0,
    livesLost: 0,
    livesLostToRocks: 0,
    livesLostToWindCones: 0,
    livesLostToSleds: 0,
    questsComplete: 0,
    questsSkipped: 0,
    totalSession: 0,
    roundsPlayed: 0,
    joinDate: null,
    timesUPressed: 0,
    totalAngleRotated: 0,
    totalHorizontalMovement: 0,
    totalVerticalMovement: 0,
    bestDistance: 0,
    totalDistance: 0,
    bestTime: 0,
    totalTime: 0,
    bestSpeed: 0,
    totalSpeed: 0,
    roundsWithHitboxes: 0,
    roundsWithredArrow: 0,
    roundsWithgreenArrow: 0,
    roundsWithblueArrow: 0,
    roundsWithorangeArrow: 0,
    roundsWithpurpleArrow: 0,
    roundsWithredSled: 0,
    roundsWithgreenSled: 0,
    roundsWithblueSled: 0,
    roundsWithgoldSled: 0,
    roundsWithpurpleSled: 0,
    roundsWithduckSled: 0,
    roundsWithredCircleTrail: 0,
    roundsWithgreenCircleTrail: 0,
    roundsWithblueCircleTrail: 0,
    roundsWithorangeCircleTrail: 0,
    roundsWithpurpleCircleTrail: 0,
    roundsWithstarTrail: 0,
    roundsWithheartTrail: 0,
    roundsWithduckSledTrail: 0,


    gameState: null,
    distance: null,
    designWidth: 1918,
    designHeight: 993,

    showHitboxes: false,

    usedSled: null,
    usedTrail: "none",
    usedSledString: null,
    usedTrailString: "none",

    playerX: null,
    playerY: null,
    playerRotate: null,
    playerWidth: 80,
    playerHeight: 80,
    lives: null,
    iFrames: null,
    roundTime: null,

    trailWidth: 30,
    trailHeight: 30,

    baseSpeed: null,
    speed: null,

    obstacleMinSpawn: 600,
    obstacleMaxSpawn: 900,
    rockWidth: 80,
    rockHeight: 80,
    coinWidth: 40,
    coinHeight: 50,
    coneStickWidth: 12,
    coneStickHeight: 19,
    coneWidth: 123,
    coneHeight: 51,

    greenArrowCost: 5,
    blueArrowCost: 5,
    orangeArrowCost: 5,
    purpleArrowCost: 5,
    redSledCost: 12,
    greenSledCost: 12,
    blueSledCost: 12,
    goldSledCost: 12,
    purpleSledCost: 12,
    duckSledCost: 36,

    redCircleTrailCost: 6,
    greenCircleTrailCost: 6,
    blueCircleTrailCost: 6,
    orangeCircleTrailCost: 6,
    purpleCircleTrailCost: 6,
    starTrailCost: 12,
    heartTrailCost: 12,
    duckSledTrailCost: 24,
    
}