export { config }

const config = {
    version: 32,
    accountName: null,

    coins: 0,
    sleds: [],
    trails: [],
    UP: 0,
    equippedUpgrades: [],
    boughtUpgrades: [],
    quest1: {active: false},
    quest2: {active: false},
    obstacleMode: "normal",

    // For stat updates
    sessionCounted: false,
    roundAngleRotated: 0,
    roundHorizontalMovement: 0,
    roundVerticalMovement: 0,

    
    // Stats
    coinsCollected: 0,
    totalCoins: 0,
    livesLost: 0,
    livesLostToRocks: 0,
    livesLostToWindCones: 0,
    livesLostToSleds: 0,
   
    quest1Complete: 0,
    quest1Skipped: 0,
    quest2Complete: 0,
    quest2Skipped: 0,
    quest3Complete: 0,
    quest3Skipped: 0,
    quest4Complete: 0,
    quest4Skipped: 0,
    quest5Complete: 0,
    quest5Skipped: 0,
    quest6Complete: 0,
    quest6Skipped: 0,

    quest101Complete: 0,
    quest101Skipped: 0,
    quest102Complete: 0,
    quest102Skipped: 0,
    quest103Complete: 0,
    quest103Skipped: 0,
    quest104Complete: 0,
    quest104Skipped: 0,
    quest105Complete: 0,
    quest105Skipped: 0,
    quest106Complete: 0,
    quest106Skipped: 0,

    extraHeartIUsed: 0,
    mindReaderUsed: 0,
    brakeControlIUsed: 0,
    brakeControlIIUsed: 0,
    slipperySidesIUsed: 0,
    slipperySidesIIUsed: 0,
    extraHeartIIUsed: 0,
    recoverySpeedIUsed: 0,
    recoverySpeedIIUsed: 0,
    magneticSledIUsed: 0,
    magneticSledIIUsed: 0,
    goldenTouchIUsed: 0,
    goldenTouchIIUsed: 0,
    moreCoinsUsed: 0,
    betterTurningIUsed: 0,
    betterTurningIIUsed: 0,
    disposableBrakesUsed: 0,
    cardboardShieldUsed: 0,
    snowballCannonUsed: 0,
    bigStickUsed: 0,
    shrinkRayUsed: 0,
    coinGoblinUsed: 0,
    strongerBrakesUsed: 0,
    moreBrakesUsed: 0,
    thickerCardboardUsed: 0,
    moreCardboardUsed: 0,
    spikeyCardboardUsed: 0,
    moreSnowUsed: 0,
    compactSnowballUsed: 0,
    lighterStickUsed: 0,
    protectiveStickUsed: 0,
    coinHogUsed: 0,
    longCoinsUsed: 0,
    strongerBeamUsed: 0,
    moreEnergyUsed: 0,
    batteryPackUsed: 0,

    disposableBrakesActivated: 0,
    cardboardShieldActivated: 0,
    snowballCannonActivated: 0,
    bigStickActivated: 0,
    shrinkRayActivated: 0,
    coinGoblinActivated: 0,

    totalSession: 0,
    roundsPlayed: 0,
    pureRoundsPlayed: 0,
    joinDate: null,

    timesUPressed: 0,
    totalAngleRotated: 0,
    totalHorizontalMovement: 0,
    totalVerticalMovement: 0,
    bestDistance: 0,
    totalDistance: 0,
    bestTime: 0,
    totalTime: 0,
    bestSpeed: 0,
    totalSpeed: 0,

    totalPureAngleRotated: 0,
    totalPureHorizontalMovement: 0,
    totalPureVerticalMovement: 0,
    bestPureDistance: 0,
    totalPureDistance: 0,
    bestPureTime: 0,
    totalPureTime: 0,
    bestPureSpeed: 0,
    totalPureSpeed: 0,

    roundsWithHitboxes: 0,

    roundsWithredArrow: 0,
    roundsWithgreenArrow: 0,
    roundsWithblueArrow: 0,
    roundsWithorangeArrow: 0,
    roundsWithpurpleArrow: 0,
    roundsWithredSled: 0,
    roundsWithgreenSled: 0,
    roundsWithblueSled: 0,
    roundsWithgoldSled: 0,
    roundsWithpurpleSled: 0,
    roundsWithduckSled: 0,
    roundsWithsubwaySurfersSled: 0,

    roundsWithredCircleTrail: 0,
    roundsWithgreenCircleTrail: 0,
    roundsWithblueCircleTrail: 0,
    roundsWithorangeCircleTrail: 0,
    roundsWithpurpleCircleTrail: 0,
    roundsWithstarTrail: 0,
    roundsWithheartTrail: 0,
    roundsWithduckSledTrail: 0,

    // End of Stats

    gameState: null,
    distance: null,
    designWidth: 1918,
    designHeight: 993,

    showHitboxes: false,

    usedSled: null,
    usedTrail: "none",
    usedSledString: null,
    usedTrailString: "none",

    deltaTime: null,
    playerX: null,
    playerY: null,
    playerRotate: null,
    playerWidth: 80,
    playerHeight: 80,
    lives: null,
    iFrames: null,
    roundTime: null,
    dash: false,
    verticalModifier: 0,

    trailWidth: 30,
    trailHeight: 30,

    baseSpeed: -200,

    obstacleSledWidth: 80,
    obstacleSledHeight: 80,

    snowballWidth: 40,
    snowballHeight: 40,
    snowballHits: 0,
    snowball: {},

    // CHANGE STARTING STATS IN UPGRADEHANDLER
    activeUpgrades: 0,
    hearts: 1,
    horizontalSpeed: 125,
    verticalSpeed: 150,
    turnSpeed: 100,
    knockback: 150,
    coinRadius: 40,
    coinDouble: 0,
    mindReader: false,

    abilityE: "none",
    abilityQ: "none",
    disposableBrakes: false,
    disposableBrakeUses: 1,
    disposableBrakePower: .95,
    bigStick: false,
    protectiveStick: false,
    bigStickCooldown: 20,
    cardboardShield: false,
    cardboardShieldDuration: 1.5,
    cardboardShieldUses: 1,
    spikeyCardboard: false,
    snowballcannon: false,
    snowballcannonUses: 1,
    snowballcannonPierce: 1,
    shrinkRay: false,
    shrinkRayDuration: 5,
    shrinkRayEffect: .75,
    shrinkRayUses: 1,
    coinGoblin: false,
    coinGoblinEffect: 2,
    coinGoblinDuration: 20,
    coinGoblinUses: 1,

    spikeyCardboardActive: 0,

    rockChance: 73,
    coinChance: 3,
    coneChance: 15,
    sledChance: 9,


    speed: null,

    obstacleMinSpawn: 600,
    obstacleMaxSpawn: 900,
    rockWidth: 80,
    rockHeight: 80,
    coinWidth: 40,
    coinHeight: 50,
    coneStickWidth: 12,
    coneStickHeight: 19,
    coneWidth: 123,
    coneHeight: 51,

    greenArrowCost: 5,
    blueArrowCost: 5,
    orangeArrowCost: 5,
    purpleArrowCost: 5,
    redSledCost: 12,
    greenSledCost: 12,
    blueSledCost: 12,
    goldSledCost: 12,
    purpleSledCost: 12,
    duckSledCost: 36,
    penguinSledCost: 36,
    sharkSledCost: 36,
    sunFishSledCost: 36,
    subwaySurfersSledCost: 72,

    redCircleTrailCost: 6,
    greenCircleTrailCost: 6,
    blueCircleTrailCost: 6,
    orangeCircleTrailCost: 6,
    purpleCircleTrailCost: 6,
    starTrailCost: 12,
    heartTrailCost: 12,
    duckSledTrailCost: 24,
    
}